spring.datasource:
  url: "jdbc:mysql://localhost/tempstation?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true"
  username: "root"
  password: "root"
  driverClassName: "com.mysql.jdbc.Driver"

server:
  port: 8080