spring.datasource:
  url: "jdbc:mysql://localhost/tempstation?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true"
  username: "root"
  password: "root"
  driverClassName: "com.mysql.jdbc.Driver"


hibernate:
  dialect: "org.hibernate.dialect.MySQL5Dialect"
  hbm2ddlAuto: "validate"


server:
  port: 8080