spring:
  datasource:
    url: "jdbc:mysql://localhost/tempstation?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.jdbc.Driver"
  jpa:
    properties.hibernate:
      dialect: "org.hibernate.dialect.MySQL5Dialect"
      hbm2ddl.auto: "validate"
      connection.release_mode: "on_close"


server:
  port: 8080
logging.level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR